micronaut:
  application:
    name: jouwBlog
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
redis:
  uri: redis://localhost
mongodb:
  uri: mongodb://localhost:27017/jouwBlog